version: '3.9'
services:
  dockerteste:
    image: douglasddrdias/dockerteste-1.0.3
    environment:
      - minha_variavel=${minha_variavel}
    volumes:
      - /home/douglas/chave:/app/arquivos
    build: .
    working_dir: /app
    network_mode: "host"
    container_name: "docker_teste_git_hub"